################################################################################
# Copyright (c) 2022-2025, NVIDIA CORPORATION. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
################################################################################

property:
  gpu-id: 0
  net-scale-factor: 0.01735207357279195
  offsets: 123.675;116.28;103.53
  model-color-format: 0
  onnx-file: ../../../models/reidentificationnet/resnet50_market1501_aicity156.onnx
  model-engine-file: ../../../models/reidentificationnet/resnet50_market1501_aicity156.onnx_b16_gpu0_fp16.engine
  infer-dims: 3;256;128
  batch-size: 16
  ## 0=FP32, 1=INT8, 2=FP16 mode
  network-mode: 2
  network-type: 100
  interval: 0
  ## Infer Processing Mode 1=Primary Mode 2=Secondary Mode
  process-mode: 2
  # ## Clustering algorithm: 0=GroupRectangle 1=DBSCAN 2=NMS 3=Hybrid 4=NoClustering
  # cluster-mode: 3
  classifier-threshold: 0
  output-tensor-meta: 1
  maintain-aspect-ratio: 0
  ## Extract embedding on "people" class only
  operate-on-class-ids: 1
  scaling-compute-hw: 1
  gie-unique-id: 2
