config:
  pgie: ../../../configs/triton-grpc/trafficcamnet_tao/pgie_trafficcamnet_config.txt
  lpd: ../../../configs/triton-grpc/LPD_us_tao/sgie_lpd_DetectNet2_us.txt
  lpr: ../../../configs/triton-grpc/lpr_us_tao/sgie_lpr_us_config.txt

