property:
  net-scale-factor: 0.01735207357279195
  offsets: 123.675;116.28;103.53
  model-color-format: 1
  onnx-file: ../../../models/retail_object_detection_binary_dino/retail_object_detection_dino_binary.onnx
  model-engine-file: ../../../models/retail_object_detection_binary_dino/retail_object_detection_dino_binary.onnx_b1_gpu0_fp32.engine
  labelfile-path: ../../../models/retail_object_detection_binary_dino/class_map.txt
  network-input-order: 0
  infer-dims: 3;540;960
  maintain-aspect-ratio: 1
  batch-size: 1
  ## 0=FP32, 1=INT8, 2=FP16 mode
  network-mode: 0
  num-detected-classes: 2
  interval: 0
  gie-unique-id: 1
  cluster-mode: 4
  output-blob-names: pred_boxes;pred_logits
  parse-bbox-func-name: NvDsInferParseCustomDDETRTAO
  custom-lib-path: ../../../post_processor/libnvds_infercustomparser_tao.so
  scaling-compute-hw: 1


#Use the config params below for NMS clustering mode
class-attrs-all:
  pre-cluster-threshold: 0.5
  topk: 300

