source-list:
   #list: file:///workspace/nvocdr/img_0.jpg;file:///workspace/nvocdr/img_1.jpg
   list: file:///workspace/nvocdr/pexels-george-morina-5266796.mp4

output:
  ## 1:file ouput  2:fake output 3:eglsink output
  type: 1
  ## 0: H264 encoder  1:H265 encoder
  codec: 0
  #encoder type 0=Hardware 1=Software
  enc-type: 0
  bitrate: 2000000
  ##The file name without suffix
  filename: test

streammux:
  width: 1280
  height: 720
  batched-push-timeout: 40000

video-template:
  #x86
  customlib-name: nvocdr_libs/x86/libnvocdr_impl.so
  #aarch64
  #customlib-name: nvocdr_libs/aarch64/libnvocdr_impl.so
  customlib-props:
    - ocdnet-engine-path:../../../models/nvocdr/ocdnet.fp16.engine
    - ocdnet-input-shape:3,736,1280
    - ocdnet-binarize-threshold:0.1
    - ocdnet-polygon-threshold:0.3
    - ocdnet-max-candidate:200
    - ocrnet-engine-path:../../../models/nvocdr/ocrnet.fp16.engine
    - ocrnet-dict-path:../../../models/nvocdr/character_list
    - ocrnet-input-shape:1,64,200
    - ocrnet-decode:Attention
