all:
	@make -C deepstream-bodypose2d-app
	@make -C deepstream-faciallandmark-app
	@make -C deepstream-emotion-app
	@make -C deepstream-emotion-app/emotion_impl
        
clean:
	@make clean -C deepstream-bodypose2d-app
	@make clean -C deepstream-faciallandmark-app
	@make clean -C deepstream-emotion-app
	@make clean -C deepstream-emotion-app/emotion_impl
