################################################################################
# SPDX-FileCopyrightText: Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
################################################################################

name: "peoplenet"
platform: "tensorrt_plan"
max_batch_size: 2
default_model_filename: "resnet34_peoplenet_int8.onnx_b2_gpu0_int8.engine"
input [
  {
    name: "input_1:0"
    data_type: TYPE_FP32
    dims: [ 3, 544, 960 ]
  }
]
output [
  {
    name: "output_bbox/BiasAdd:0"
    data_type: TYPE_FP32
    dims: [ 12, 34, 60 ]
  },
  {
    name: "output_cov/Sigmoid:0"
    data_type: TYPE_FP32
    dims: [ 3, 34, 60 ]
  }
]

instance_group [
  {
    kind: KIND_GPU
    count: 1
    gpus: 0
  }
]
