all:
	@make -C deepstream-mdx-perception-app
	@make -C deepstream-nvocdr-app
	@make -C deepstream-pose-classification
	@make -C deepstream_lpr_app
clean:
	@make clean -C deepstream-mdx-perception-app
	@make clean -C deepstream-nvocdr-app
	@make clean -C deepstream-pose-classification
	@make clean -C deepstream_lpr_app
