all:
	@make -C deepstream-bodypose2d-app
	@make -C deepstream-faciallandmark-app
	@make -C deepstream-emotion-app
	@make -C deepstream-emotion-app/emotion_impl
	@make -C deepstream-gaze-app
	@make -C deepstream-gaze-app/gazeinfer_impl
	@make -C deepstream-gesture-app
	@make -C deepstream-heartrate-app/heartrateinfer_impl
	@make -C deepstream-heartrate-app
	@make -C deepstream-mdx-perception-app
	@make -C deepstream-nvocdr-app
	@make -C deepstream-pose-classification
clean:
	@make clean -C deepstream-bodypose2d-app
	@make clean -C deepstream-faciallandmark-app
	@make clean -C deepstream-emotion-app
	@make clean -C deepstream-emotion-app/emotion_impl
	@make clean -C deepstream-gaze-app
	@make clean -C deepstream-gaze-app/gazeinfer_impl
	@make clean -C deepstream-gesture-app
	@make clean -C deepstream-heartrate-app/heartrateinfer_impl
	@make clean -C deepstream-heartrate-app
	@make clean -C deepstream-mdx-perception-app
	@make clean -C deepstream-nvocdr-app
	@make clean -C deepstream-pose-classification
